# Generated by Django 6.0.7 on 2026-07-09 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Tartib raqami')),
                ('emoji', models.CharField(default='🎮', max_length=10, verbose_name='Emoji')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Bolimcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(verbose_name='Tartib raqami')),
                ('emoji', models.CharField(default='⭐', max_length=10, verbose_name='Emoji')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolimchalar', to='home.bolim', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': "Bo'limcha",
                'verbose_name_plural': "Bo'limchalar",
                'ordering': ['order'],
            },
        ),
    ]
