# Generated by Django 6.0.7 on 2026-07-09 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_seed_bolimlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Tartib raqami')),
                ('daraja', models.CharField(choices=[('oson', 'Oson'), ('orta', "O'rta"), ('qiyin', 'Qiyin'), ('tanqidiy', 'Tanqidiy')], max_length=10, verbose_name='Daraja')),
                ('matn', models.TextField(verbose_name='Savol matni')),
                ('variant_a', models.CharField(max_length=255, verbose_name='A varianti')),
                ('variant_b', models.CharField(max_length=255, verbose_name='B varianti')),
                ('variant_c', models.CharField(max_length=255, verbose_name='C varianti')),
                ('togri_javob', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1, verbose_name="To'g'ri javob")),
                ('bolimcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='home.bolimcha', verbose_name="Bo'limcha")),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SavolNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='Yulduzlar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='home.savol', verbose_name='Savol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savol natijasi',
                'verbose_name_plural': 'Savol natijalari',
            },
        ),
        migrations.AddConstraint(
            model_name='savol',
            constraint=models.UniqueConstraint(fields=('bolimcha', 'order'), name='unique_savol_order'),
        ),
        migrations.AddConstraint(
            model_name='savolnatija',
            constraint=models.UniqueConstraint(fields=('user', 'savol'), name='unique_user_savol'),
        ),
    ]
